[package]
name = "grepr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
regex = "1"
walkdir = "2"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
sys-info = "0.9"
