[package]
name = "grepr"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33"
regex = "1"
walkdir = "2"

[dev-dependencies]
assert_cmd = "1"
predicates = "1"
rand = "0.8"
sys-info = "0.9"
