[package]
name = "fortuner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.1.4", features = ["derive"] }
rand = "0.8.5"
regex = "1.10.2"
walkdir = "2.4.0"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
